"""Sync models

Revision ID: 0f201023ac7b
Revises: a32721fb9c05
Create Date: 2025-01-28 11:46:40.153744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f201023ac7b'
down_revision: Union[str, None] = 'a32721fb9c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_temp_id', table_name='users')
    op.drop_index('ix_users_temp_username', table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index('ix_users_temp_username', 'users', ['username'], unique=1)
    op.create_index('ix_users_temp_id', 'users', ['id'], unique=False)
    # ### end Alembic commands ###
